MUENTIP/Controllers/EditProfileController.cs
using Microsoft.AspNetCore.Mvc;
using MUENTIP.Data;
using MUENTIP.ViewModels;
using Microsoft.AspNetCore.Identity;
using MUENTIP.Models;
using Microsoft.EntityFrameworkCore;
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using System.Diagnostics;
using Newtonsoft.Json;

namespace MUENTIP.Controllers
{
    public class EditProfileController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly UserManager<User> _userManager;
        private readonly Cloudinary _cloudinary;

        public EditProfileController(ApplicationDBContext context, UserManager<User> userManager, Cloudinary cloudinary)
        {
            _context = context;
            _userManager = userManager;
            _cloudinary = cloudinary;   

        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var userClass = await _context.Users
                .Include(u => u.InterestedTags)
                .ThenInclude(it => it.Tag)
                .FirstOrDefaultAsync(u => u.Id == user.Id);

            var tagsFromDb = await _context.Tags
                .Select(t => new TagFilterViewModel { TagName = t.TagName })
                .ToListAsync();

            var model = new MyProfileViewModel
            {
                UserName = user.UserName,
                ProfileImageLink = user.ProfileImageLink,
                Email = user.Email,
                Info = user.Info,
                BirthDate = user.BirthDate,
                Gender = user.Gender,
                Education = user.Education,
                Address = user.Address,
                InterestedTags = user.InterestedTags?.Select(it => it.TagName).ToList() ?? new List<string>(),
                availableTags = tagsFromDb,
                showCreate = user.ShowCreate,
                showParticipate = user.ShowParticipate
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Image(IFormFile file)
        {   
            if (file == null || file.Length == 0)
            {
                return BadRequest(new { message = "No file uploaded" });
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }

            using var stream = file.OpenReadStream();
            var uploadParams = new ImageUploadParams
            {
                File = new FileDescription(file.FileName, stream),
                Folder = "uploads"
            };

            

            var uploadResult = await _cloudinary.UploadAsync(uploadParams);
            var imageUrl = uploadResult.SecureUrl.ToString();

            return Ok(new { imageUrl });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MyProfileViewModel model)
        {   

            var user = await _userManager.GetUserAsync(User);

            

            if (user != null)
            {

                if (model.UserName != user.UserName && _context.Users.Any(u => u.UserName == model.UserName))
                {
                    return Json(new { success = false, message = "UserName already taken" });
                }

                if (model.Email != user.Email && _context.Users.Any(u => u.Email == model.Email))
                {
                    return Json(new { success = false, message = "Email already in used" });
                }
                if (model.BirthDate != null)
                {
                    if (model.BirthDate > DateOnly.FromDateTime(DateTime.Now))
                    {
                        return Json(new { success = false, message = "Birthdate is invalid." });
                    }
                }

                user.UserName = model.UserName;
                user.NormalizedUserName = model.UserName.ToUpper();
                user.Email = model.Email;
                user.NormalizedEmail = model.Email.ToUpper();
                user.Info = model.Info;
                user.BirthDate = model.BirthDate;
                user.Gender = model.Gender;
                user.Education = model.Education;
                user.Address = model.Address;
                user.ShowCreate = model.showCreate;
                user.ShowParticipate = model.showParticipate;

                if (!string.IsNullOrEmpty(model.ProfileImageLink))
                {
                    if (!string.IsNullOrEmpty(user.ProfileImageLink))
                    {
                        var oldImageUrl = new Uri(user.ProfileImageLink);
                        var fullImageUrl = oldImageUrl.AbsolutePath;
                        var imagePath = fullImageUrl.Substring(fullImageUrl.IndexOf("uploads"));
                        var imagePathWithoutExtension = Path.GetFileNameWithoutExtension(imagePath);
                        var deleteParams = new DelResParams()
                        {
                            PublicIds = new List<string> { $"uploads/{imagePathWithoutExtension}" },
                            Type = "upload",
                            ResourceType = ResourceType.Image
                        };

                        var result = _cloudinary.DeleteResources(deleteParams);
                    }
                        user.ProfileImageLink = model.ProfileImageLink;

                }


                var JSONtags = model.InterestedTags;

                List<string> tags = JsonConvert.DeserializeObject<List<string>>(JSONtags[0]);
                var currentTags = await _context.InterestIn
                    .Where(interest => interest.UserId == user.Id)
                    .ToListAsync();


                _context.InterestIn.RemoveRange(currentTags);

                foreach (var tag in tags)
                {

                    var tagExists = await _context.Tags.AnyAsync(t => t.TagName == tag);
                    if (!tagExists)
                    {
                        return Json(new { success = false, message = $"Tag '{tag}' does not exist." });
                    }


                    var InterestIn = new InterestIn
                    {
                        UserId = user.Id,
                        TagName = tag

                    };

                    _context.InterestIn.Add(InterestIn);
                }

                await _context.SaveChangesAsync();

                return Json(new { success = true, message = $"{user.Id}"});
            }

            return Json(new { success = false, message = "Unorthorizes" });
        }

    }
}

MUENTIP/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using MUENTIP.Data;
using MUENTIP.ViewModels;
using Microsoft.AspNetCore.Identity;
using MUENTIP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.SignalR;
namespace MUENTIP.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly UserManager<User> _userManager;

        public ProfileController(ApplicationDBContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string id)
        {

            var userClass = await _context.Users
                .Where(u => u.Id == id)
                .Select(u => new
                {
                    u.Id,
                    u.UserName,
                    u.ProfileImageLink,
                    u.Email,
                    u.Info,
                    u.BirthDate,
                    u.Gender,
                    u.Education,
                    u.Address,
                    u.ShowCreate,
                    u.ShowParticipate,
                    InterestedTags = u.InterestedTags.Select(it => it.Tag.TagName).ToList(),

                    CreatedActivities = u.CreatedActivities.OrderByDescending(a => a.ActivityId).Select(a => new
                    {
                        a.ActivityId,
                        a.Title,
                        a.Location,
                        a.StartDateTime,
                        a.EndDateTime,
                        a.DeadlineDateTime,
                        a.ApplyMax,
                        ApplyCount = a.Applications.Count(),
                        Tags = a.ActivityTags.Select(at => at.Tag.TagName).ToList(),
                        OwnerName = a.User.UserName
                    }).ToList(),

                    Participations = u.Participations.OrderByDescending(a => a.ActivityId).Select(p => new
                    {
                        Activity = p.Activity != null ? new
                        {
                            p.Activity.ActivityId,
                            p.Activity.Title,
                            OwnerName = p.Activity.User.UserName,
                            p.Activity.Location,
                            p.Activity.StartDateTime,
                            p.Activity.EndDateTime,
                            p.Activity.DeadlineDateTime,
                            p.Activity.ApplyMax,
                            ApplyCount = p.Activity.Applications.Count(),
                            Tags = p.Activity.ActivityTags.Select(at => at.Tag.TagName).ToList()
                        } : null
                    }).ToList()
                })
                .FirstOrDefaultAsync();

            List<ActivityCardViewModel> CreatedActivityFromDb = new();
            List<ActivityCardViewModel> NonApprovedActivityFromDb = new();
            List<ActivityCardViewModel> ApprovedActivityFromDb = new();

            if (userClass != null)
            {
                CreatedActivityFromDb = userClass.CreatedActivities
                    .Select(t => new ActivityCardViewModel
                    {
                        ActivityId = t.ActivityId,
                        Title = t.Title,
                        Owner = t.OwnerName,
                        Location = t.Location,
                        StartDateTime = t.StartDateTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                        EndDateTime = t.EndDateTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                        DeadlineDateTime = t.DeadlineDateTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                        ApplyMax = t.ApplyMax,
                        ApplyCount = t.ApplyCount,
                        TagsList = t.Tags
                    })
                    .ToList();



                ApprovedActivityFromDb = userClass.Participations
                    .Where(p => p.Activity != null)
                    .Select(p => new ActivityCardViewModel
                    {
                        ActivityId = p.Activity.ActivityId,
                        Title = p.Activity.Title,
                        Owner = p.Activity.OwnerName,
                        Location = p.Activity.Location,
                        StartDateTime = p.Activity.StartDateTime.ToString("yyyy-MM-ddTHH:mm"),
                        EndDateTime = p.Activity.EndDateTime.ToString("yyyy-MM-ddTHH:mm"),
                        DeadlineDateTime = p.Activity.DeadlineDateTime.ToString("yyyy-MM-ddTHH:mm"),
                        ApplyMax = p.Activity.ApplyMax,
                        ApplyCount = p.Activity.ApplyCount,
                        TagsList = p.Activity.Tags
                    })
                    .ToList();
            }
            else
            {
                return NotFound();
            }
            var tagsFromDb = await _context.Tags
                        .Select(t => new TagFilterViewModel { TagName = t.TagName })
                        .ToListAsync();
            var model = new MyProfileViewModel
            {
                Id = userClass.Id,
                UserName = userClass.UserName,
                ProfileImageLink = userClass.ProfileImageLink,
                Email = userClass.Email,
                Info = userClass.Info,
                BirthDate = userClass.BirthDate,
                Gender = userClass.Gender,
                Education = userClass.Education,
                Address = userClass.Address,
                InterestedTags = userClass.InterestedTags,
                createdActivity = CreatedActivityFromDb,

                approvedActivity = ApprovedActivityFromDb,
                availableTags = tagsFromDb,
                showCreate = userClass.ShowCreate,
                showParticipate = userClass.ShowParticipate
            };

            return View(model);
        }

    }
}

MUENTIP/Views/EditProfile/Index.cshtml
@using MUENTIP.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager
@{
    ViewData["Title"] = "EditProfile";
    var user = await UserManager.GetUserAsync(User);
    var userId = user.Id;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/MyProfile/my_profile_page.css">
    <link rel="stylesheet" href="~/css/MyProfile/edit-profile.css">
</head>

<body>
    <header>Edit Profile</header>
    <a href="@Url.Action("Index", "Profile", new { id = userId })">
        <button type="button" class="cancel-btn"><</button>
    </a>

    <div id="tagModal" class="tag-modal">
        <div class="modal-content">
            <span class="cancel-select-tag-btn" onclick="closeTagModal()">&times;</span>
            <h2>Select Tags</h2>
            <ul id="availableTags">

            </ul>
        </div>
    </div>

    <form id="EditForm">
        <input type="hidden" id="profileImageLink" name="ProfileImageLink">
        <div class="profile-card">
            <div class="profile-picture">
                @if (Model.ProfileImageLink != null)
                {
                    <img src="@Model.ProfileImageLink" alt="Profile Picture" id="profile-img" style="width: 150px; height: 150px; border-radius: 50%;" />
                }
                else
                {
                    <img src="/img/default-profile.png" alt="Profile Picture" id="profile-img" style="width: 150px; height: 150px; border-radius: 50%;" />
                }
            </div>
            <input type="file" id="fileInput" style="display: none;" accept="image/*" onchange="uploadImage()">
            <button type="button" class="_button" id="fileInputButton" onclick="document.getElementById('fileInput').click()">Upload</button>

            <div class="detail-profile">
                <div class="form-group">
                    <label for="Name">Name : </label>
                    <input type="text" id="Name" name="UserName" value="@Model.UserName" required />
                </div>

                <div class="form-group">
                    <label for="Email">Email : </label>
                    <input type="email" id="Email" name="Email" value="@Model.Email" required />
                </div>

                <div class="form-group">
                    <label for="Detail">About me : </label>
                    <textarea id="Detail" name="Info">@Model.Info</textarea>
                </div>

                <div class="form-group">
                    <label for="Birthday">Birthday : </label>
                    <input type="date" id="Birthday" name="BirthDate" value="@Model.BirthDate?.ToString("yyyy-MM-dd")" />
                </div>

                <div class="form-group">
                    <label for="Gender">Gender : </label>
                    <input type="text" id="Gender" name="Gender" value="@Model.Gender"/>
                </div>

                <div class="form-group">
                    <label for="Education">Education : </label>
                    <input type="text" id="Education" name="Education" value="@Model.Education" />
                </div>

                <div class="form-group">
                    <label for="Address">Address : </label>
                    <input type="text" id="Address" name="Address" value="@Model.Address" />
                </div>

                <div class="form-group">
                    <label for="InterestedTags">Tags : </label>
                    <ul id="tag-nav" class="tag-nav">
                        @foreach (var tag in Model.InterestedTags)
                        { 
                            <li class="hot-tag-ele">@tag
                                <button type="button" class="remove-tag-btn" data-tag="@tag" onclick="removeTagFromProfile('@tag')">X</button>
                            </li>
                        }
                    </ul>
                    <button type="button"id="addTagBtn" class="hot-tag-ele"><div class="add-btn">+</div></button>
                </div>
                <div class="form-group">
                    <label for="showCreate"><input type="checkbox" id="showCreate" name="showCreate"
                        @if (Model.showCreate)
                        {
                            @:checked
                        }
                    /> Show your created activities? </label>
                    
                </div>
                <div class="form-group">
                    
                    <label for="showParticipate">
                        <input type="checkbox" id="showParticipate" name="showParticipate"
                            @if (Model.showParticipate)
                            {
                                @:checked
                            } 
                        />
                        Show your participation history?
                    </label>
                    
                </div>
            </div>
            <p id="error"></p>
          
            <div class="form-group">
                <button type="submit" id="submitButton" class="_button">Save Changes</button>
            </div>
        </div>
            
    </form>

   

    <script>
        var activityModel = @Html.Raw(Json.Serialize(Model)); 
        var interestedTags = @Html.Raw(Json.Serialize(Model.InterestedTags));
        
    </script>

    <script src="~/js/MyProfile/edit_profile_page.js"></script>

</body>
</html>